name: "Echo something"
description: "Echo something to test calling action from another repo"
inputs:
  message:
    description: "The message that we're going to echo out"
    default: "This is the default message"
    required: true
    type: string
  name:
    description: "The person to whom we should address our message"
    default: "First Last"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - run: echo "This message is for ${{ inputs.name }}':' ${{ inputs.message }}"
      shell: bash